# Generated by Django 3.1.4 on 2020-12-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20201213_1244'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.png', upload_to='thumbnails/%Y/%m/%d/'),
        ),
    ]
